### ISSUE TITLE
rosrun xacro xacro.py does not work

### ISSUE THREAD

**Issue by mikeferguson** [ros/xacro#1]
Brought up on the ros users mailing list after Tully announced new debs:

I'm not sure what all the cmake-wizardry is trying to do in xacro-extras.cmake, but it appears the problem here is actually that xacro.py in <install>/lib/xacro/ is not executable as it would be if it were brought in via a "install(PROGRAMS ..." type of cmake command.

**Comment by tkruse** [comment]
I believe setup.py should now read:

```
import os
from distutils.core import setup
from catkin_pkg.python_setup import generate_distutils_setup, get_package_bin_destination

d = generate_distutils_setup(
    packages=['xacro'],
    package_dir={'': 'src'},
    data_files=[(get_package_bin_destination('xacro'),
                 ['scripts/xacro.py'])],
)
```

as we do not want xacro.py to go into the global bin folder, and in CMakelists, the line

```
install(FILES scripts/xacro.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

should be removed, as it does not preserve permissions.

**Comment by tkruse** [comment]
Alternatively, remove mention of xarco.py in setup.py, and change CMakeLists.txt:

```
- install(FILES scripts/xacro.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
+ install(PROGRAMS scripts/xacro.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

**Comment by ablasdel** [comment]
Fixed in 490cbb8a3b4d1eb633697113a51bcc466c61cf6b

re-releasing asap

**Comment by ablasdel** [comment]
This is released and will be available as soon as it gets pushed out by the farm.

**Comment by bit-pirate** [comment]
Is this bugfix in 1.7.3?  (http://www.ros.org/debbuild/groovy.html)
I can't update until this fix is in public, since xacro is important for me.

**Comment by ablasdel** [comment]
Yes this bug fix is in 1.7.3

I will talk to Tully and have this pushed to public ASAP.

On Mar 4, 2013, at 16:19, Marcus Liebhardt notifications@github.com wrote:

Is this bugfix in 1.7.3? (http://www.ros.org/debbuild/groovy.html)
I can't update until this fix is in public, since xacro is important for me.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ros/xacro/issues/1#issuecomment-14416016
.

**Comment by corot** [comment]
I have upgraded to xacro 1.7.3 and still have the same error when using xacro from a launch file. Fort example, when I launch

```
roslaunch turtlebot_rviz_launchers view_model.launch 
```

I get 

```
...
while processing /opt/kobuki_rosmake/turtlebot/turtlebot_bringup/launch/includes/_robot.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: no such command [/opt/ros/groovy/share/xacro/xacro.py '/opt/kobuki_rosmake/turtlebot/turtlebot_description/robots/kobuki_hexagons_kinect.urdf.xacro']. 

Param xml is <param command="$(arg urdf_file)" name="robot_description"/>
```

If I execute xacro with rosrun, no problem. Looks like the $(find xacro)/xacro.py on launch files assumes that xacro is still a non-catkin package, and so the scripts are on share directory instead of the catkin standard (bin).

**Comment by tkruse** [comment]
What I said was: "Alternatively, remove mention of xacro.py in setup.py, and change CMakeLists.txt: ..." 
Patch 490cbb8 only did one of those 2 things.

**Comment by bit-pirate** [comment]
roslaunch-related issue is now tracked by new issue https://github.com/ros/xacro/issues/2.
